version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    restart: always
    networks:
      - welo-network

networks:
  welo-network:
    driver: bridge