services:
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
      - ./data-test/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGO_INITDB_DATABASE=chat-app
    networks:
      - welo-network
    restart: always

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123456
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=123456
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    networks:
      - welo-network
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          memory: 128M


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --requirepass 123456
    networks:
      - welo-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      - AWS_ACCESS_KEY_ID=AKIAWMFUPRI3QPUSMTNK
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=ap-southeast-1
      - AWS_BUCKET_NAME=test-9-4
      - MONGO_URI=mongodb://mongo:27017/chat-app
      - JWT_SECRET=123456
      - JWT_REFRESH=123456
      - EMAIL_USER=hkthanh.iuh@gmail.com
      - EMAIL_PASSWORD=sbxa wyee cpwe nnsm
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - welo-network
    restart: always

volumes:
  mongo-data:
  redis-data:

networks:
  welo-network:
    driver: bridge
